// flow-typed signature: 44873935b0ab5d9a9f0f43bfaa23fe9f
// flow-typed version: <<STUB>>/esdoc-node_v^1.0.3/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esdoc-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'esdoc-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'esdoc-node/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'esdoc-node/index' {
  declare module.exports: $Exports<'esdoc-node'>;
}
declare module 'esdoc-node/index.js' {
  declare module.exports: $Exports<'esdoc-node'>;
}
declare module 'esdoc-node/test.js' {
  declare module.exports: $Exports<'esdoc-node/test'>;
}
